name: CI Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - run: echo "PASSO 1 - inicio"

      - uses: actions/checkout@v4

      - run: echo "PASSO 2 - checkout ok"

      - run: docker --version

      - run: echo "PASSO 3 - Docker ok "

      - run: docker build -t fastapi-lab .

      - run: echo "PASSO 4 - build ok"

      - run: docker run -d -p 8000:8000 fastapi-lab

      - run: echo "PASSO 5 - Testar endpoint"

      - run: |
          sleep 5
          curl http://localhost:8000/health

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd fastapi-ci-cd-lab
            docker compose down
            docker compose up -d --build
